"""Initial migration (no partitioning)

Revision ID: b9acd7afbe4b
Revises: 
Create Date: 2025-06-05 22:23:35.046301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9acd7afbe4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentiment'), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_ticker'), 'news', ['ticker'], unique=False)
    op.drop_index('idx_popular_searches_count', table_name='popular_searches')
    op.drop_index('idx_popular_searches_last_searched', table_name='popular_searches')
    op.drop_table('popular_searches')
    op.drop_index('idx_news_cache_expires_at', table_name='news_cache')
    op.drop_index('idx_news_cache_symbol', table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index('news_sentiment', table_name='News')
    op.drop_index('news_ticker_created_at', table_name='News')
    op.drop_index('news_ticker_published_at', table_name='News')
    op.drop_table('News')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('News',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"News_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sentimentScore', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('publishedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment', postgresql.ENUM('positive', 'negative', 'neutral', name='enum_News_sentiment'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='News_pkey')
    )
    op.create_index('news_ticker_published_at', 'News', ['ticker', 'publishedAt'], unique=False)
    op.create_index('news_ticker_created_at', 'News', ['ticker', 'createdAt'], unique=False)
    op.create_index('news_sentiment', 'News', ['sentiment'], unique=False)
    op.create_table('news_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='news_cache_pkey'),
    sa.UniqueConstraint('symbol', name='news_cache_symbol_key')
    )
    op.create_index('idx_news_cache_symbol', 'news_cache', ['symbol'], unique=False)
    op.create_index('idx_news_cache_expires_at', 'news_cache', ['expires_at'], unique=False)
    op.create_table('popular_searches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('last_searched', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='popular_searches_pkey'),
    sa.UniqueConstraint('symbol', name='popular_searches_symbol_key')
    )
    op.create_index('idx_popular_searches_last_searched', 'popular_searches', [sa.text('last_searched DESC')], unique=False)
    op.create_index('idx_popular_searches_count', 'popular_searches', [sa.text('count DESC')], unique=False)
    op.drop_index(op.f('ix_news_ticker'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
